Accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from Restaurant.models import Profile,Contact

contact = Contact.objects.latest('updated')
profile = Profile.objects.all()

app_name = "Accounts"
urlpatterns = [
    path('login', views.loginview, name='login'),
    path('logout', views.logoutview, name='logout'),
    path('register', views.registerview, name='register'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name = "password_reset.html",extra_context={"profile":profile,'contact':contact,}), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html",extra_context={"profile":profile,'contact':contact,}), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html",extra_context={"profile":profile,'contact':contact,}), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html",extra_context={"profile":profile,'contact':contact,}), name='password_reset_complete'),
]

Blog/urls.py
from django.urls import path
from . import views

app_name = "Blog"
urlpatterns = [
    path('blog/', views.home, name='blog'),
    path('blog/<int:page>/', views.home, name='pageblog'),
    path('blog/<slug:slug>/', views.detail, name='blogdetails'),
    path('blog/category/<slug:slug>/', views.category, name='category'),
    path('blog/category/<slug:slug>/page/<int:page>', views.category, name='category2'),
]

Personal_Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Restaurant.urls'), name="Restaurant"),
    path('', include('Accounts.urls'), name="Accounts"),
    path('', include('Blog.urls'), name="Blog"),
    path('', include('django.contrib.auth.urls'), name=""),
]

urlpatterns = urlpatterns + staticfiles_urlpatterns()
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Restaurant/urls.py
from django.urls import path
from . import views

app_name = "Restaurant"
urlpatterns = [
    path('', views.home, name='home'),
    # path('duplicate', views.home2, name='home2'),
]

Blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# from ckeditor.fields import RichTextField

# Managers
class ArticleManager(models.Manager):
    def publishd(self):
        return self.filter(status="p")


# 1 - Category # 1 - Category # 1 - Category # 1 - Category # 1 - Category
class Category(models.Model):
    title = models.CharField(max_length = 150)
    slug = models.SlugField(unique=True, max_length=100)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '02 - Category'


# 2 - Article # 2 - Article # 2 - Article # 2 - Article # 2 - Article # 2 - Article
class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE, editable=False, default=1)
    title = models.CharField(max_length = 150)
    slug = models.SlugField(unique=True, max_length=100)
    category = models.ManyToManyField(Category,related_name="articles")
    description = models.TextField()
    image = models.ImageField(upload_to="Blog_Image")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    STATUS_CHOICES = (('d','Draft'),('p','Published'))
    status = models.CharField(max_length = 1,choices=STATUS_CHOICES)

    def category_publishd(self):
        return self.category.filter(status=True)

    objects = ArticleManager()
    
    def __str__(self):
        return self.title     

    class Meta:
        verbose_name_plural = '01 - Article'


# 3 - Comment # 3 - Comment # 3 - Comment # 3 - Comment # 3 - Comment # 3 - Comment 
class Comment(models.Model): 
    article = models.ForeignKey(Article,on_delete=models.CASCADE,related_name="comments")
    user = models.CharField(max_length = 50)
    content = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=False) 

    class Meta:
        verbose_name_plural = '03 - Comment'
        ordering = ('created',) 

    def __str__(self): 
        return 'Comment by {} on {}'.format(self.user, self.article) 


# 4 - Reply_Comment Reply_Comment Reply_Comment Reply_Comment Reply_Comment 
class Reply_Comment(models.Model): 
    comments = models.ForeignKey(Comment,on_delete=models.CASCADE,related_name="recomments")
    user = models.ForeignKey("auth.User",on_delete = models.CASCADE, editable=False, default=1)
    content = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 

    class Meta:
        verbose_name_plural = '04 - Reply Comment'
        ordering = ('created',) 

    def __str__(self): 
        return 'Comment Reply by Admin {} --> on the : {}'.format(self.user, self.comments) 

Blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user', 'content')
        widgets = {
            'user': forms.TextInput(attrs={'placeholder': 'Enter Your Name {Required}'}),
            'content': forms.Textarea(attrs={'placeholder': 'Enter Your Comment {Required}'})}

Blog/views.py
from django.db.models import Count
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import Article, Category
from Restaurant.models import Profile,Contact
from .forms import CommentForm


def home(request):
    articles_list = Article.objects.filter(status="p").order_by('-publish')
    
    paginator = Paginator(articles_list, 6)
    page = request.GET.get('page',1)
    profile = Profile.objects.all()
    contact = Contact.objects.latest('updated')

    try:
        result = paginator.page(page)
    except PageNotAnInteger:
        result = paginator.page(1)
    except EmptyPage:
        result = paginator.page(paginator.num_pages)

    context = {
        "articles":result,
        "profile":profile,
        "contact":contact,
    }

    return render(request, 'Blog/blog.html',context)



def detail(request, slug):

    article = get_object_or_404(Article, slug = slug, status="p")
    comments = article.comments.filter(active=True)

    context = {
        # "article":Article.objects.filter(slug = slug),
        "article" : article,
        "comments" : comments,
        "form" : CommentForm,
        "categories" : Category.objects.filter(articles__status='p').annotate(posts_count=Count('articles')),
        "category" : Category.objects.filter(status=True),
        "profile" : Profile.objects.all(),
        "contact" : Contact.objects.latest('updated')
    }

    if request.method == "POST":
        commentform = CommentForm(request.POST)
        if commentform.is_valid():
            newcomment = commentform.save(commit=False)
            newcomment.article = article
            newcomment.save()
    else:
        commentform = CommentForm()

    return render(request, 'Blog/blog-detail.html',context)



def category(request, slug):
    category = get_object_or_404(Category, slug = slug, status=True)
    articles_list = category.articles.publishd()
    paginator = Paginator(articles_list, 9)
    articles = request.GET.get('page',1)

    try:
        result = paginator.page(articles)
    except PageNotAnInteger:
        result = paginator.page(1)
    except EmptyPage:
        result = paginator.page(paginator.num_pages)

    context = {
        "category" : category,
        "articles" : result,
    }

    return render(request, 'Blog/category.html',context)

Blog/templates/layout.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <title>{% block pagetitle %} {% endblock %}</title>
        <meta name="description" content="Personal Responsive Restaurant">
        <meta name="keywords" content="Sana Zarei">
        <meta charset="utf-8">
        <meta name="author" content="Sana Zarei">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />
        <!-- animation --> 
        <link rel="stylesheet" href="{% static 'css/animate.css' %}" />
        <!-- bootstrap --> 
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
        <!-- et line icon --> 
        <link rel="stylesheet" href="{% static 'css/et-line-icons.css' %}" />
        <!-- font awesome -->
        <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
        <!-- revolution slider -->
        <link rel="stylesheet" href="{% static 'css/extralayers.css' %}" />
        <link rel="stylesheet" href="{% static 'css/settings.css' %}" />
        <!-- magnific popup -->
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
        <!-- owl carousel -->
        <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
        <link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}" />
        <link rel="stylesheet" href="{% static 'css/full-slider.css' %}" />
        <!-- text animation -->
        <link rel="stylesheet" href="{% static 'css/text-effect.css' %}" />
        <!-- hamburger menu  -->
        <link rel="stylesheet" href="{% static 'css/menu-hamburger.css' %}" />
        <!-- common -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <!-- responsive -->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />

    </head>
    <body>
        <!-- head section -->
        <section class="content-top-margin page-title page-title-small border-bottom-light border-top-light">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-12 wow fadeInUp" data-wow-duration="300ms">
                        <!-- page title -->
                        <h1 class="black-text">{% block title %}  {% endblock %}</h1>
                        <!-- end page title -->
                    </div>
                    <div class="col-md-4 col-sm-12 breadcrumb text-uppercase wow fadeInUp xs-display-none" data-wow-duration="600ms">
                        <!-- breadcrumb -->
                        <ul>
                            <li><a href="{% url 'Restaurant:home' %}">Home</a></li>
                            <li><a href="{% url 'Blog:blog' %}">{% block breadcrumb0 %}  {% endblock %}</a></li>
                            <li>{% block breadcrumb %}  {% endblock %}</li>
                        </ul>
                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </section>
        <!-- end head section -->

        {% block main %} 
        <!-- content section -->

        <!-- end content section -->
        {% endblock %}

        <!-- footer -->
        <footer>
            <div class=" bg-white footer-top">
                <div class="container">
                    <div class="row margin-four">
                        <div class="col-md-4 col-sm-4 text-center"><i class="icon-phone small-icon black-text"></i><h6 class="black-text margin-two no-margin-bottom">{{ contact.phone }}</h6></div>
                        <div class="col-md-4 col-sm-4 text-center"><i class="icon-map-pin small-icon black-text"></i><h6 class="black-text margin-two no-margin-bottom">{{ contact.address }}</h6></div>
                        <div class="col-md-4 col-sm-4 text-center"><i class="icon-envelope small-icon black-text"></i><h6 class="margin-two no-margin-bottom"><a href="mailto:{{ contact.email }}" class="black-text">{{ contact.email }}</a></h6></div>
                    </div>
                </div>
            </div>
            <div class="container footer-middle">
                <div class="row margin-four no-margin-bottom">
                    <div class="col-md-6 col-sm-12 sm-text-center sm-margin-bottom-four">
                        <ul class="list-inline footer-link text-uppercase">
                            <li><a href="{% url 'Restaurant:home' %}">Home</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 col-sm-12 footer-social text-right sm-text-center">
                        {% for item in profile %}
                        <a target="_blank" href="{{ item.link }}"><i class="fa-brands fa-{{item.name}}" aria-hidden="true"></i></a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="container-fluid bg-dark-gray footer-bottom">
                <div class="container">
                    <div class="row margin-three">
                        <!-- copyright -->
                        <div class="col-md-6 col-sm-6 col-xs-12 copyright text-left letter-spacing-1 xs-text-center xs-margin-bottom-one">
                            &copy; 2022 Restaurant Theme is proudly powered by SANA ZAREI.
                        </div>
                        <!-- end copyright -->
                    </div>
                </div>
            </div>

            <a href="javascript:;" class="scrollToTop"><i class="fa fa-angle-up"></i></a> 

        </footer>
        <!-- end footer -->
        <!-- javascript libraries / javascript files set #1 --> 
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script> 
        <script type="text/javascript" src="{% static 'js/bootstrap-hover-dropdown.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.easing.1.3.js' %}"></script> 
        <script type="text/javascript" src="{% static 'js/skrollr.min.js' %}"></script>  
        <script type="text/javascript" src="{% static 'js/smooth-scroll.js' %}"></script>
        <!-- jquery appear -->
        <script type="text/javascript" src="{% static 'js/jquery.appear.js' %}"></script>
        <!-- animation -->
        <script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
        <!-- page scroll -->
        <script type="text/javascript" src="{% static 'js/page-scroll.js' %}"></script>
        <!-- easy piechart-->
        <script type="text/javascript" src="{% static 'js/jquery.easypiechart.js' %}"></script>
        <!-- parallax -->
        <script type="text/javascript" src="{% static 'js/jquery.parallax-1.1.3.js' %}"></script>
        <!--portfolio with shorting tab --> 
        <script type="text/javascript" src="{% static 'js/jquery.isotope.min.js' %}"></script> 
        <!-- owl slider  -->
        <script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
        <!-- magnific popup  -->
        <script type="text/javascript" src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/popup-gallery.js' %}"></script>
        <!-- text effect  -->
        <script type="text/javascript" src="{% static 'js/text-effect.js' %}"></script>
        <!-- revolution slider  -->
        <script type="text/javascript" src="{% static 'js/jquery.tools.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.revolution.js' %}"></script>
        <!-- counter  -->
        <script type="text/javascript" src="{% static 'js/counter.js' %}"></script>
        <!-- countTo -->
        <script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
        <!-- fit videos  -->
        <script type="text/javascript" src="{% static 'js/jquery.fitvids.js' %}"></script>
        <!-- imagesloaded  -->
        <script type="text/javascript" src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
        <!-- hamburger menu-->
        <script type="text/javascript" src="{% static 'js/classie.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/hamburger-menu.js' %}"></script>
        <!-- setting --> 
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

        <script>
            const form3 = document.getElementById("registerform");
            form3.addEventListener("submit", submitHandler);

            function submitHandler(event) {
                event.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "{% url 'Accounts:register' %}",
                    data: $("#registerform").serialize(),
                    dataType: "json",
                    success: function sucessHandler(data)
                    {
                        if (data.msg === "Success") 
                        {
                            alert("Sign Up completed");
                            document.getElementById("registerform").reset();
                            window.location.href = "{% url 'Accounts:login' %}";
                        }
                        else if (data.msg === "Error")
                        {
                            alert("This username or Email has already been registered");
                        }
                    }
                });
            }
        </script>

        <script>
            const form3 = document.getElementById("addcomment");
            form3.addEventListener("submit", submitHandler);

            function submitHandler(event) {
                event.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "{% url 'Blog:category' %}",
                    data: $("#addcomment").serialize(),
                    dataType: "json",
                    success: function sucessHandler(data)
                    {
                        if (data.msg === "Success") 
                        {
                            alert("Sign Up completed");
                            document.getElementById("addcomment").reset();
                        }
                        else if (data.msg === "Error")
                        {
                            alert("This username or Email has already been registered");
                        }
                    }
                });
            }
        </script>
    </body>
</html>