Accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from Restaurant.models import Profile,Contact

contact = Contact.objects.latest('updated')
profile = Profile.objects.all()

app_name = "Accounts"
urlpatterns = [
    path('login', views.loginview, name='login'),
    path('logout', views.logoutview, name='logout'),
    path('register', views.registerview, name='register'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name = "password_reset.html",extra_context={"profile":profile,'contact':contact,}), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html",extra_context={"profile":profile,'contact':contact,}), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html",extra_context={"profile":profile,'contact':contact,}), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html",extra_context={"profile":profile,'contact':contact,}), name='password_reset_complete'),
]

Blog/urls.py
from django.urls import path
from . import views

app_name = "Blog"
urlpatterns = [
    path('blog/', views.home, name='blog'),
    path('blog/<int:page>/', views.home, name='pageblog'),
    path('blog/<slug:slug>/', views.detail, name='blogdetails'),
    path('blog/category/<slug:slug>/', views.category, name='category'),
    path('blog/category/<slug:slug>/page/<int:page>', views.category, name='category2'),
]

Personal_Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Restaurant.urls'), name="Restaurant"),
    path('', include('Accounts.urls'), name="Accounts"),
    path('', include('Blog.urls'), name="Blog"),
    path('', include('django.contrib.auth.urls'), name=""),
]

urlpatterns = urlpatterns + staticfiles_urlpatterns()
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ProfileModel(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="user_profile")

    class Meta:
        verbose_name="user"
        verbose_name_plural="user"

Accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import ProfileModel
from django.contrib.auth import authenticate,login,logout,get_user_model

User = get_user_model()



class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'placeholder': 'Enter Your Username {Required}','class': 'input-round big-input'}))
    password = forms.CharField(max_length=100,widget=forms.PasswordInput(attrs={'placeholder': 'Enter Your Password {Required}','class': 'input-round big-input'}))

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)



class ProfileRegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'placeholder': 'Enter Your Username {Required}','class': 'input-round big-input'}))
    email = forms.CharField(max_length=100,widget=forms.EmailInput(attrs={'placeholder': 'Enter Your Email {Required}','class': 'input-round big-input'}))
    password = forms.CharField(max_length=100,widget=forms.PasswordInput(attrs={'placeholder': 'Enter Your Password {Required}','class': 'input-round big-input'}))

    class Meta:
        model = ProfileModel
        fields = ('username', 'email', 'password')

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        # if password1 != password2:
        #     raise forms.ValidationError("Password must match")
        username_check = User.objects.filter(username=username)
        if username_check.exists():
            raise forms.ValidationError("This username has already been registered")
        email_check = User.objects.filter(email=email)
        if email_check.exists():
            raise forms.ValidationError("This Email has already been registered")        
        return super(ProfileRegisterForm, self).clean(*args, **kwargs)

Accounts/views.py
from audioop import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from .forms import UserLoginForm, ProfileRegisterForm
from Restaurant.models import Profile,Contact
from django.contrib.auth.views import PasswordResetDoneView



def loginview(request):

    contact = Contact.objects.latest('updated')
    profile = Profile.objects.all()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse('Restaurant:home'))
        else:
            context = {"username":username, "ErrorMessage":": Username or Password Error","profile":profile, "form":UserLoginForm}
            return render(request, 'login.html',context)
    else:
        return render(request, 'Accounts/login.html',{"form":UserLoginForm,"profile":profile,'contact':contact})


def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('Restaurant:home'))



def registerview(request):

    contact = Contact.objects.latest('updated')
    profile = Profile.objects.all()

    if request.method=="POST":
        profileregisterform=ProfileRegisterForm(request.POST or None)
        if profileregisterform.is_valid():
            user = User.objects.create_user(username=profileregisterform.cleaned_data["username"],email=profileregisterform.cleaned_data['email'],password=profileregisterform.cleaned_data['password'])
            user.save()
            return JsonResponse({'msg':'Success'})
            # return HttpResponseRedirect(reverse('Accounts:login'))
        else:
            return JsonResponse({'msg':'Error'})
    else:
        profileregisterform=ProfileRegisterForm()

    return render(request, 'Accounts/register.html',{"form":profileregisterform,"profile":profile,'contact':contact})

Accounts/templates/Accounts/login.html
{% extends "layout.html" %}

{% block pagetitle %} Login {% endblock %}
{% block title %} Login {% endblock %}
{% block breadcrumb %} Login {% endblock %}

{% block main %}
<section class="bg-gray wow fadeIn">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-sm-8 col-xs-11 center-col xs-no-padding">
                <form id="loginform" method="POST">
                    <p style="color:red;">{{username}}{{ErrorMessage}}</p>
                    {% csrf_token %}
                    <div class="form-group no-margin-bottom">
                        <label class="text-uppercase">Username</label>
                        {{ form.username }}
                    </div>
                    <div class="form-group no-margin-bottom">
                        <label class="text-uppercase">Password</label>
                        {{ form.password }}
                    </div>
                    <button class="btn highlight-button-dark btn-small btn-round margin-five no-margin-right" type="submit">Login</button>
                    <a href="{% url 'Accounts:register' %}" class="display-block text-uppercase">Register</a>
                    <a href="{% url 'Accounts:password_reset' %}" class="display-block text-uppercase">Forgot Password?</a>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Accounts/templates/Accounts/password_reset.html
{% extends "layout.html" %}

{% block pagetitle %} Reset Password {% endblock %}
{% block title %} Reset Password {% endblock %}
{% block breadcrumb %} Reset Password {% endblock %}

{% block main %}
    <section class="bg-gray wow fadeIn">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-8 col-xs-11 center-col xs-no-padding">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group no-margin-bottom">
                            {{ form }}
                        </div>
                        <button class="btn highlight-button-dark btn-small btn-round margin-five no-margin-right" type="submit">Reset My Password</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Accounts/templates/Accounts/password_reset_done.html
{% extends "layout.html" %}

{% block pagetitle %} Reset Password {% endblock %}
{% block title %} Reset Password {% endblock %}
{% block breadcrumb %} Reset Password {% endblock %}

{% block main %}
    <section class="bg-gray wow fadeIn">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-8 col-xs-11 center-col xs-no-padding">
                    <h3>Password reset Complete</h3>
                    <br>
                    <p>Your Password Reset. You May go Ahead And Login Now <p>
                    <a href="{% url 'Accounts:login' %}" class="btn highlight-button-dark btn-small btn-round margin-five no-margin-right">Login</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Accounts/templates/Accounts/password_reset_form.html
{% extends "layout.html" %}

{% block pagetitle %} Reset Password {% endblock %}
{% block title %} Reset Password {% endblock %}
{% block breadcrumb %} Reset Password {% endblock %}


{% block main %}
    <section class="bg-gray wow fadeIn">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-8 col-xs-11 center-col xs-no-padding">
                    <h3>Enter New Password</h3>
                    <br>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="fieldWrapper">
                            <label for="password" class="text-uppercase">New password:</label>
                            {{ form.new_password1 }}
                        </div>
                        <div class="fieldWrapper">
                            <label for="password" class="text-uppercase">New password confirmation:</label>
                            {{ form.new_password2 }}
                        </div>
                        {% comment %} {{ form }} {% endcomment %}
                        <button class="btn highlight-button-dark btn-small btn-round margin-five no-margin-right" type="submit">Update My Password</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Accounts/templates/Accounts/password_reset_sent.html
{% extends "layout.html" %}

{% block pagetitle %} Reset Password {% endblock %}
{% block title %} Reset Password {% endblock %}
{% block breadcrumb %} Reset Password {% endblock %}


{% block main %}
    <section class="bg-gray wow fadeIn">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-8 col-xs-11 center-col xs-no-padding">
                    <h3>Password reset sent</h3>
                    <br>
                    <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<p>
                    <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Accounts/templates/Accounts/register.html
{% extends "layout.html" %}

{% block pagetitle %} Register {% endblock %}
{% block title %} Register {% endblock %}
{% block breadcrumb %} Register {% endblock %}

{% block main %} 
    <section class="bg-gray wow fadeIn">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-8 col-xs-11 center-col xs-no-padding">
                    <form id="registerform" method="POST">
                        {% csrf_token %}
                        <div class="form-group no-margin-bottom">
                            <label class="text-uppercase">Username</label>
                            {{ form.username }}
                        </div>
                        <div class="form-group no-margin-bottom">
                            <label class="text-uppercase">Email</label>
                            {{ form.email }}
                        </div>
                        <div class="form-group no-margin-bottom">
                            <label class="text-uppercase">Password</label>
                            {{ form.password }}
                        </div>
                        <button class="btn highlight-button-dark btn-small btn-round margin-five no-margin-right" type="submit">Register Now</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}