Blog/urls.py
from django.urls import path
from . import views

app_name = "Blog"
urlpatterns = [
    path('blog/', views.home, name='blog'),
    path('blog/<int:page>/', views.home, name='pageblog'),
    path('blog/<slug:slug>/', views.detail, name='blogdetails'),
    path('blog/category/<slug:slug>/', views.category, name='category'),
    path('blog/category/<slug:slug>/page/<int:page>', views.category, name='category2'),
]

Personal_Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Restaurant.urls'), name="Restaurant"),
    path('', include('Accounts.urls'), name="Accounts"),
    path('', include('Blog.urls'), name="Blog"),
    path('', include('django.contrib.auth.urls'), name=""),
]

urlpatterns = urlpatterns + staticfiles_urlpatterns()
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# from ckeditor.fields import RichTextField

# Managers
class ArticleManager(models.Manager):
    def publishd(self):
        return self.filter(status="p")


# 1 - Category # 1 - Category # 1 - Category # 1 - Category # 1 - Category
class Category(models.Model):
    title = models.CharField(max_length = 150)
    slug = models.SlugField(unique=True, max_length=100)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '02 - Category'


# 2 - Article # 2 - Article # 2 - Article # 2 - Article # 2 - Article # 2 - Article
class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE, editable=False, default=1)
    title = models.CharField(max_length = 150)
    slug = models.SlugField(unique=True, max_length=100)
    category = models.ManyToManyField(Category,related_name="articles")
    description = models.TextField()
    image = models.ImageField(upload_to="Blog_Image")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    STATUS_CHOICES = (('d','Draft'),('p','Published'))
    status = models.CharField(max_length = 1,choices=STATUS_CHOICES)

    def category_publishd(self):
        return self.category.filter(status=True)

    objects = ArticleManager()
    
    def __str__(self):
        return self.title     

    class Meta:
        verbose_name_plural = '01 - Article'


# 3 - Comment # 3 - Comment # 3 - Comment # 3 - Comment # 3 - Comment # 3 - Comment 
class Comment(models.Model): 
    article = models.ForeignKey(Article,on_delete=models.CASCADE,related_name="comments")
    user = models.CharField(max_length = 50)
    content = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=False) 

    class Meta:
        verbose_name_plural = '03 - Comment'
        ordering = ('created',) 

    def __str__(self): 
        return 'Comment by {} on {}'.format(self.user, self.article) 


# 4 - Reply_Comment Reply_Comment Reply_Comment Reply_Comment Reply_Comment 
class Reply_Comment(models.Model): 
    comments = models.ForeignKey(Comment,on_delete=models.CASCADE,related_name="recomments")
    user = models.ForeignKey("auth.User",on_delete = models.CASCADE, editable=False, default=1)
    content = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 

    class Meta:
        verbose_name_plural = '04 - Reply Comment'
        ordering = ('created',) 

    def __str__(self): 
        return 'Comment Reply by Admin {} --> on the : {}'.format(self.user, self.comments) 

Blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user', 'content')
        widgets = {
            'user': forms.TextInput(attrs={'placeholder': 'Enter Your Name {Required}'}),
            'content': forms.Textarea(attrs={'placeholder': 'Enter Your Comment {Required}'})}

Blog/views.py
from django.db.models import Count
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import Article, Category
from Restaurant.models import Profile,Contact
from .forms import CommentForm


def home(request):
    articles_list = Article.objects.filter(status="p").order_by('-publish')
    
    paginator = Paginator(articles_list, 6)
    page = request.GET.get('page',1)
    profile = Profile.objects.all()
    contact = Contact.objects.latest('updated')

    try:
        result = paginator.page(page)
    except PageNotAnInteger:
        result = paginator.page(1)
    except EmptyPage:
        result = paginator.page(paginator.num_pages)

    context = {
        "articles":result,
        "profile":profile,
        "contact":contact,
    }

    return render(request, 'Blog/blog.html',context)



def detail(request, slug):

    article = get_object_or_404(Article, slug = slug, status="p")
    comments = article.comments.filter(active=True)

    context = {
        # "article":Article.objects.filter(slug = slug),
        "article" : article,
        "comments" : comments,
        "form" : CommentForm,
        "categories" : Category.objects.filter(articles__status='p').annotate(posts_count=Count('articles')),
        "category" : Category.objects.filter(status=True),
        "profile" : Profile.objects.all(),
        "contact" : Contact.objects.latest('updated')
    }

    if request.method == "POST":
        commentform = CommentForm(request.POST)
        if commentform.is_valid():
            newcomment = commentform.save(commit=False)
            newcomment.article = article
            newcomment.save()
    else:
        commentform = CommentForm()

    return render(request, 'Blog/blog-detail.html',context)



def category(request, slug):
    category = get_object_or_404(Category, slug = slug, status=True)
    articles_list = category.articles.publishd()
    paginator = Paginator(articles_list, 9)
    articles = request.GET.get('page',1)

    try:
        result = paginator.page(articles)
    except PageNotAnInteger:
        result = paginator.page(1)
    except EmptyPage:
        result = paginator.page(paginator.num_pages)

    context = {
        "category" : category,
        "articles" : result,
    }

    return render(request, 'Blog/category.html',context)

Blog/templates/Blog/blog-detail.html
{% extends "layout.html" %}
{% load static %}

{% block pagetitle %} {{article.title}} {% endblock %}
{% block title %} BLOG Details {% endblock %}
{% block breadcrumb0 %} BLOG {% endblock %}
{% block breadcrumb %} BLOG Details {% endblock %}

{% block main %}
    <!-- content section -->
    <section class="wow fadeIn">
        <div class="container">
            <div class="row">
                <!-- content  -->
                <div class="col-md-8 col-sm-8">
                    <!-- post title  -->
                    <h2 class="blog-details-headline text-black">{{article.title}}</h2>
                    <!-- end post title  -->
                    <!-- post date and categories  -->
                    <div class="blog-date no-padding-top">Posted by <a href="">{{article.author}}</a> | {{article.publish}} | {% for item in article.category.all %} <a href="{% url 'Blog:category' item.slug %}">{{item.title}}</a>, {% endfor %}  </div>
                    <!-- end date and categories   -->
                    <!-- post image -->
                    <div class="blog-image margin-eight"><img src="{{article.image.url}}" alt="" ></div>
                    <!-- end post image -->
                    <!-- post details text -->
                    <div class="blog-details-text">
                        {{article.description|linebreaks}}
                        <div class="blog-date no-padding-top margin-eight no-margin-bottom">
                            <!-- post tags -->
                            <h5 class="widget-title margin-one no-margin-top">Tags</h5>
                            {% for item in article.category.all %}
                                <a href="{% url 'Blog:category' item.slug %}">{{item.title}},</a>
                            {% endfor %}
                        </div>
                        <!-- end post tags -->
                    </div>
                    <!-- end post details text -->
                    <!-- about author -->
                    {% comment %} <div class="text-center margin-ten no-margin-bottom about-author text-left bg-gray">
                        <div class="blog-comment text-left clearfix no-margin">
                            <!-- author image -->
                            <a class="comment-avtar no-margin-top"><img src="{% static 'images/user.png' %}" alt=""></a>
                            <!-- end author image -->
                            <!-- author text -->
                            <div class="comment-text overflow-hidden position-relative">
                                <h5 class="widget-title">About The Author</h5>
                                <p class="blog-date no-padding-top">Paul Scrivens - Creative Head</p>
                                <p class="about-author-text no-margin">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
                            </div>
                            <!-- end author text -->
                        </div>
                    </div> {% endcomment %}
                    <!-- end about author -->
                    <!-- social icon -->
                    {% comment %} <div class="text-center border-bottom margin-ten padding-four no-margin-top">
                        <a href="#" class="btn social-icon social-icon-large button"><i class="fa-brands fa-telegram"></i></a>
                        <a href="#" class="btn social-icon social-icon-large button"><i class="fa-brands fa-whatsapp"></i></a>
                    </div> {% endcomment %}
                    <!-- end social icon -->
                    <!-- post comment -->
                    <div class="blog-comment-main xs-no-padding-top">
                        <h5 class="widget-title">Blog Comments</h5>
                        {% for item in comments %}
                        <div class="blog-comment">
                            <a class="comment-avtar"><img src="{% static 'images/user.png' %}" alt=""></a>
                            <div class="comment-text overflow-hidden position-relative">
                                <p class="blog-date no-padding-top"><a href="#">{{item.user}}</a>, {{item.created}} </p>
                                <p>{{item.content|linebreaks}}</p>
                            </div>
                            <div class="blog-comment clearfix">
                                {% for reply in item.recomments.all %}
                                <a class="comment-avtar"><img src="{% static 'images/user.png' %}" alt=""></a>
                                <div class="comment-text overflow-hidden position-relative">
                                    <p class="blog-date no-padding-top"><a href="#">{{reply.user}}</a>, {{reply.created}} </p>
                                    <p>{{reply.content}}</p>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% empty %}
                        <br> <br> <br>
                        <p>No Comments Here.</p>
                        {% endfor %}
                    </div>
                    <!-- end post comment -->
                        <!-- comment form -->
                        <div class="blog-comment-form-main">
                            <h5 class="widget-title margin-five no-margin-top">Add a comment</h5>
                            <div class="blog-comment-form">
                                <form method="POST" id="addcomment">
                                    {% csrf_token %}
                                    {% comment %} <input type="text" name="name" placeholder="Name"> {% endcomment %}
                                    {{form.user}}
                                    {% comment %} <input type="text" name="email" placeholder="Email"> {% endcomment %}
                                    {% comment %} <textarea name="comment" placeholder="Comment"></textarea> {% endcomment %}
                                    {{form.content}}
                                    <input type="submit" name="send message" value="send message" class="highlight-button-dark btn btn-small no-margin-bottom">
                                </form>
                            </div>
                        </div>
                        <!-- end comment form -->
                </div>
                <!-- end content  -->
                <!-- sidebar  -->
                <div class="col-md-3 col-sm-4 col-md-offset-1 sidebar xs-margin-top-ten">
                    <!-- widget  -->
                    <div class="widget">
                        <h5 class="widget-title font-alt">Categories</h5>
                        <div class="thin-separator-line bg-dark-gray no-margin-lr"></div>
                        <div class="widget-body">
                            <ul class="category-list">
                                {% for item in categories %}
                                <li><a href="{% url 'Blog:category' item.slug %}">{{item.title}}<span>{{item.posts_count}}</span></a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <!-- end widget  -->
                    <!-- widget  -->
                    <div class="widget">
                        <h5 class="widget-title font-alt">Tags Cloud</h5>
                        <div class="thin-separator-line bg-dark-gray no-margin-lr"></div>
                        <div class="widget-body tags">
                            {% for item in categories %}
                            <a href="">{{item.title}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- end widget  -->
                </div>
                <!-- end sidebar  -->
            </div>
        </div>
    </section>
    <!-- end content section -->
{% endblock %}

Blog/templates/Blog/blog.html
{% extends "layout.html" %}
{% load static %}

{% block pagetitle %} BLOG {% endblock %}
{% block title %} BLOG {% endblock %}
{% block breadcrumb0 %} BLOG {% endblock %}
{% block breadcrumb %}  {% endblock %}

{% block main %}
    <!-- content section -->
        <section class="wow fadeIn">
            <div class="container">
                <div class="row blog-3col">
                    {% for item in articles %}
                    <!-- post item -->
                    <div class="col-md-4 col-sm-6 col-xs-6 blog-listing wow fadeInUp" data-wow-duration="300ms">
                        {% if item.image %}
                        <div class="blog-image"><a href="{% url 'Blog:blogdetails' item.slug %}"><img src="{{item.image.url}}" alt=""></a></div>
                        {% endif %}
                        <div class="blog-details">
                            <div class="blog-date">Posted by <a href="">{{item.author}}</a> | {{item.publish}}</div>
                            <div class="blog-title"><a href="{% url 'Blog:blogdetails' item.slug %}">{{item.title}}</a></div>
                            <div class="blog-short-description">{{item.description|truncatewords:15}}</div>
                            <div class="separator-line bg-black no-margin-lr"></div>
                            {% comment %} <div>
                                <a href="#" class="blog-like"><i class="fa fa-heart-o">Likes</i></a>
                                <a href="#" class="blog-share"><i class="fa fa-share-alt">Share</i></a>
                                <a href="#" class="comment"><i class="fa fa-comment-o">{{item.comment_count}} comment</i></a>
                            </div> {% endcomment %}
                        </div>
                    </div>
                    <!-- end post item -->        
                    {% endfor %}     
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 wow fadeInUp">
                    {% if articles.has_other_pages %}
                        <!-- pagination -->
                        <div class="pagination">
                            {% if articles.has_previous %}
                            <a href="?page={{articles.previous_page_number}}"><img src="{% static 'images/arrow-pre-small.png' %}" alt=""/></a>
                            {% endif %}

                            {% for i in articles.paginator.page_range %}
                            {% if articles.number == i %}
                            <a href="?page={{articles.next.page_number}}" class="active">{{i}}</a>
                            {% else %}
                            <a href="?page={{i}}">{{i}}</a>
                            {% endif %}
                            {% endfor %}

                            {% if articles.has_next %}
                            <a href="?page={{articles.next_page_number}}"><img src="{% static 'images/arrow-next-small.png' %}" alt=""/></a>
                            {% endif %}
                        </div>
                        <!-- end pagination -->
                    {% endif %}
                    </div>
                </div>
            </div>
        </section>
        <!-- end content section -->
{% endblock %}

Blog/templates/Blog/category.html
{% extends "layout.html" %}
{% load static %}

{% block pagetitle %} BLOG {% endblock %}
{% block title %} BLOG {% endblock %}
{% block breadcrumb0 %} BLOG {% endblock %}
{% block breadcrumb %} BLOG {% endblock %}

{% block main %}
    <!-- content section -->
        <section class="wow fadeIn">
            <div class="container">
                <div class="row blog-3col">
                    {% comment %} {% for item in category.articles.all %} {% endcomment %}
                    {% for item in articles %}
                    <!-- post item -->
                    <div class="col-md-4 col-sm-6 col-xs-6 blog-listing wow fadeInUp" data-wow-duration="300ms">
                        <div class="blog-image"><a href="{% url 'Blog:blogdetails' item.slug %}"><img src="{{item.image.url}}" alt=""></a></div>
                        <div class="blog-details">
                            <div class="blog-date">Posted by <a href="">{{item.author}}</a> | {{item.publish}}</div>
                            <div class="blog-title"><a href="{% url 'Blog:blogdetails' item.slug %}">{{item.title}}</a></div>
                            <div class="blog-short-description">{{item.description|truncatewords:15}}</div>
                            <div class="separator-line bg-black no-margin-lr"></div>
                        </div>
                    </div>
                    <!-- end post item -->        
                    {% endfor %}     
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 wow fadeInUp">
                    {% if articles.has_other_pages %}
                        <!-- pagination -->
                        <div class="pagination">
                            {% if articles.has_previous %}
                            <a href="?page={{articles.previous_page_number}}"><img src="{% static 'images/arrow-pre-small.png' %}" alt=""/></a>
                            {% endif %}

                            {% for i in articles.paginator.page_range %}
                            {% if articles.number == i %}
                            <a href="?page={{articles.next.page_number}}" class="active">{{i}}</a>
                            {% else %}
                            <a href="?page={{i}}">{{i}}</a>
                            {% endif %}
                            {% endfor %}

                            {% if articles.has_next %}
                            <a href="?page={{articles.next_page_number}}"><img src="{% static 'images/arrow-next-small.png' %}" alt=""/></a>
                            {% endif %}
                        </div>
                        <!-- end pagination -->
                    {% endif %}
                    </div>
                </div>
            </div>
        </section>
        <!-- end content section -->
{% endblock %}